from typing import Annotated, Dict, List, TypedDict, Optional, Literal
from langgraph.graph.message import add_messages
from pydantic import BaseModel
from playwright.async_api import Page


_MAX_PLAN_HISTORY = 6
_MAX_EXTRACTED_ENTRIES = 6
_MAX_EXTRACTED_TOTAL_CHARS = 50000
_MAX_EXTRACTED_ITEM_CHARS = 12000
_MAX_REASONING_ENTRIES = 16
_MAX_REASONING_ITEM_CHARS = 3200
_MAX_ITEM_RESULTS = 200


def get_mission_goal(state) -> str:
    """The mission objective, preferred over re-reading the raw first message.

    `mission_goal` is the planner's clarified one-sentence goal. Before the
    planner has run (or if it produced nothing) fall back to the user's first
    message. The legacy "USER REQUEST: " prefix is stripped for runs resumed
    from checkpoints created before app.py stopped adding it.
    """
    goal = (state.get("mission_goal") or "").strip()
    if goal:
        return goal
    messages = state.get("messages") or []
    first = messages[0] if messages else None
    if isinstance(first, dict):
        content = str(first.get("content", ""))
    elif hasattr(first, "content"):
        content = str(first.content)
    else:
        content = str(first) if first is not None else ""
    content = content.strip()
    if content.startswith("USER REQUEST: "):
        content = content[len("USER REQUEST: "):].strip()
    return content or "Unknown intent"

def append_plan(old_plans: List[List[str]], new_plan: List[str]) -> List[List[str]]:
    """
    Keeps a history of every version of the plan.
    old_plans: The history of previous plans.
    new_plan: The latest plan generated by the Orchestrator.
    """
    if old_plans is None:
        return [new_plan]
    # Append the new plan version to the history and keep it bounded.
    return (old_plans + [new_plan])[-_MAX_PLAN_HISTORY:]


def append_extracted(old: List[str], new: List[str]) -> List[str]:
    """Append newly extracted content chunks (for state reducer)."""
    if new is None:
        return old or []
    items = new if isinstance(new, list) else [new] if new else []
    cleaned = [str(item)[:_MAX_EXTRACTED_ITEM_CHARS] for item in items if item]
    combined = (old or []) + cleaned
    combined = combined[-_MAX_EXTRACTED_ENTRIES:]

    total_chars = sum(len(chunk) for chunk in combined)
    while combined and total_chars > _MAX_EXTRACTED_TOTAL_CHARS:
        removed = combined.pop(0)
        total_chars -= len(removed)
    return combined


def append_dom_cache(old: List[str], new: List[str]) -> List[str]:
    """Append DOM/text snapshots, keeping only the most recent few entries."""
    if new is None:
        return old or []
    items = new if isinstance(new, list) else [new]
    combined = (old or []) + items
    # keep last 5 snapshots
    return combined[-5:]


def append_reasoning(old: List[str], new: List[str]) -> List[str]:
    """Append reasoning entries, keeping the most recent to prevent unbounded growth."""
    if new is None:
        return old or []
    items = new if isinstance(new, list) else [new] if new else []
    clipped = [str(item)[:_MAX_REASONING_ITEM_CHARS] for item in items if item]
    combined = (old or []) + clipped
    return combined[-_MAX_REASONING_ENTRIES:]


def append_item_results(old: List[Dict], new: List[Dict]) -> List[Dict]:
    """Append per-work-item outcome records (for state reducer)."""
    if new is None:
        return old or []
    items = new if isinstance(new, list) else [new]
    combined = (old or []) + [item for item in items if isinstance(item, dict)]
    return combined[-_MAX_ITEM_RESULTS:]


class ProjectState(TypedDict):
    # Standard conversation history
    messages: Annotated[list, add_messages]

    # Mission identity
    mission_goal: Optional[str]  # Planner's clarified one-sentence goal; MAIN_GOAL for every agent

    # Browser-specific context
    current_url: str
    screenshot: Optional[str]  # Base64 encoded
    screenshot_meta: Optional[Dict]  # Capture metadata for freshness/escalation checks
    dom_cache: Annotated[List[str], append_dom_cache]  # Recent DOM/text snapshots for navigation
    last_page_snapshot: Optional[str]  # Post-action page snapshot (structured evidence, not a log line)

    # Plan tracking
    plan_history: Annotated[List[List[str]], append_plan]  # History of all plan versions
    current_plan: List[str]  # The active plan steps
    current_step_index: int  # Which step we're on (0-based)
    number_of_transactions: int  # Number of transactions completed
    step_attempts: int  # Attempts made on the current step
    stall_cycles: int  # Consecutive verify cycles without step completion (forces fallback when capped)
    stall_tracked_step: int  # Plan step index the stall counter is tied to
    max_step_attempts: int  # Max retries before aborting
    max_transactions: int  # Max graph transactions before aborting
    goal_retry_cycles: int  # Consecutive final-step retries where step passed but the goal did not

    # Work queue for bulk tasks ("apply to these 20 jobs"): the outer loop over
    # items is deterministic; only the per-item plan is LLM-generated.
    work_items: Optional[List[Dict]]  # Each item: {"description": str, "url": Optional[str]}
    current_item_index: int  # Index into work_items for the item being worked
    item_results: Annotated[List[Dict], append_item_results]  # One outcome record per finished item

    # Coordination fields
    plan_status: Literal["MAINTAIN", "UPDATE", "CREATE", "NEEDS_CLARIFICATION"]
    current_task: str  # The specific task for executor
    reasoning_log: Annotated[List[str], append_reasoning]
    extracted_content: Annotated[List[str], append_extracted]  # Gathered text from pages (for present step)
    is_complete: bool
    handoff_interaction: bool
    needs_fallback: bool
    last_step_complete: bool
    mission_failed: bool
    abort_reason: Optional[str]
    pending_sensitive_action: Optional[Dict]  # Pending sensitive action awaiting explicit user confirmation
    # The user's answer to that checkpoint. An approved record carries the exact
    # action and args that were proposed; the graph routes it straight to the
    # executor, which dispatches it as-is (no model call) and clears it.
    sensitive_action_approval: Optional[Dict]
    requested_context: Optional[List[str]]  # Missing context requested from fallback for user clarification

    # User-provided credentials (service logins, personal info, payment, experience)
    user_credentials: Optional[Dict]

    # Autonomy policy chosen by the user (see autonomy.py); None means the default
    # confirm-irreversible policy.
    autonomy_policy: Optional[Dict]

    # Mission status — living document accessible to all agents
    mission_status: Optional[str]          # Rendered markdown status page
    status_signals: Optional[Dict]         # Accumulated structured signals (HITL events, milestones, login phase, etc.)

    # Structured control-plane fields (prefer these over parsing reasoning_log / task markers)
    last_execution_event: Optional[Dict]   # Last executor action/args/status (see schema.LastExecutionEvent)
    step_intent: Optional[str]             # schema.StepIntent value for current_task
    recovery_context: Optional[Dict]       # base_task, recovery_hint, continuation_objective when fallback applies
