from typing import Annotated, List, TypedDict, Optional, Literal
from langgraph.graph.message import add_messages
from pydantic import BaseModel

def append_plan(old_plans: List[List[str]], new_plan: List[str]) -> List[List[str]]:
    """
    Keeps a history of every version of the plan.
    old_plans: The history of previous plans.
    new_plan: The latest plan generated by the Orchestrator.
    """
    if old_plans is None:
        return [new_plan]
    # Append the new plan version to the history
    return old_plans + [new_plan]

class ProjectState(TypedDict):
    # Conversation history
    messages: Annotated[list, add_messages]

    # Browser-specific context
    current_url: str
    screenshot: Optional[str]

    # Coordination fields
    plan_history: Annotated[List[List[str]], append_plan]
    plan_status: Literal["MAINTAIN", "UPDATE", "CREATE"]
    current_task: str
    reasoning_log: List[str]
    is_complete: bool
    needs_fallback: bool